# This is the minimum version number required.
fastlane_version "1.110.0"

default_platform :ios

platform :ios do

  desc "Build an adhoc distribution version"
  desc "This will also make sure the profile is up to date"
  lane :adhoc do
    if is_ci?
      cert(keychain_path: 'travis.keychain', keychain_password: 'travis')
      sigh(adhoc: true)
    end
    gym(scheme: 'AutomaticSigning')
  end

end
