# This is the minimum version number required.
fastlane_version "1.110.0"

default_platform :ios

platform :ios do

  desc "Build an adhoc distribution version"
  desc "This will also make sure the profile is up to date"
  lane :adhoc do
    xcargs = {}
    if is_ci?
      # import the private key
      FastlaneCore::KeychainImporter.import_file('../travis_signing_assets.p12', '../travis.keychain', 
        keychain_password: 'travis', certificate_password: ENV['TRAVIS_KEY_PASSWORD'])
      profile_uuid = sigh(adhoc: true)
      xcargs = {
        'PROVISIONING_PROFILE_app' => profile_uuid
      }
    end
    gym(scheme: 'AutomaticSigning', xcargs: xcargs)
  end

end
